# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Felix Seidel
email: hello-felix@seidel.me
description: > # this means to ignore newlines until "baseurl:"
  Welcome! This is Felix Seidel's portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://felix.seidel.me" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      header_nav: true
      footer_nav: false

# Build settings
markdown: kramdown
include:
  - .nojekyll
  - .well-known
  - _pages
  - _static
exclude:
  - node_modules
  - bower_components
  - package.json
  - bower.json
  - Gruntfile.coffee
  - Rakefile
  - Gemfile
  - .ruby-gemset
  - .ruby-version
  - deploy.sh
  - docker-compose.yml
  - Dockerfile
  - README.md

gems:
  - jekyll-sitemap
